package com.AngularWithSpringBoot.services;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

@Service
public class AiChatService {

    @Value("${ai.api.key}")
    private String apiKey;

    private final RestTemplate restTemplate = new RestTemplate();

    public String getAiAnswer(String question) {

        // ✅ Validation
        if (question == null || question.trim().isEmpty()) {
            throw new IllegalArgumentException("Question cannot be null or empty");
        }

        String url = "https://api.openai.com/v1/responses";

        // ✅ Headers
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.setBearerAuth(apiKey);

        // ✅ Request Body
        Map<String, Object> body = new HashMap<>();
        body.put("model", "gpt-4.1-mini");
        body.put("input", question);

        HttpEntity<Map<String, Object>> request =
                new HttpEntity<>(body, headers);

        // ✅ API Call
        ResponseEntity<Map> response =
                restTemplate.postForEntity(url, request, Map.class);

        Map responseBody = response.getBody();

        // ✅ Safety checks
        if (responseBody == null || !responseBody.containsKey("output")) {
            return "No response from AI";
        }

        List output = (List) responseBody.get("output");
        if (output == null || output.isEmpty()) {
            return "No output generated by AI";
        }

        Map firstOutput = (Map) output.get(0);
        List content = (List) firstOutput.get("content");
        if (content == null || content.isEmpty()) {
            return "No content in AI response";
        }

        Map firstContent = (Map) content.get(0);

        // ✅ FINAL STRING RETURN
        return firstContent.get("text").toString();
    }
}
